print("Hello! Im Aurelia and these are some thing about me! PSA: press enter at the end of each fact!")
input()
print("My name is Aurelia Emery I am 12 years old and i was born in Seattle Washington")
input()
print("One of my favorite things to do is ride horses!")
input()
print("I lease a horse named Benny, he is a yellow pony and i love him very much!")
input()
print("I also love art sosososoososooso much i think its so much fun!")
input()
print("I think its time now to flip the roles and you can tell me sme facts about you!")
input()
name = input("What is your name? Enter here:")
print(f"Ooh {name} is such a fun name!")
input()
hobbie = input("What is your favorite hobbie,sport or activity? Enter here:")
print(f"I ")