print("Hello girllll its me Samtha from the bus stop!")
one = input("Type Message:")
print("Wait im sorry whats your name again i need to save your contact?")
name = input("Type Message:")
print(f"{name} is such a cool name!")
two = input("Type Message:")
print ("Do you wanna hear what happened with stephanie and jim-bob!?")
three = input ("Enter yes or no: ")
if three == "no" :
    print("oh okay then i have nothing to tell you...")
    ten = input("Type Message:")
    print("im gonna go, bye.")
if three == "yes" :
    print("okay so Jim-bob told Stephanie she dident wannabe freinds with him so guess what she did!")
    four = input("Type Message:")
    print("She STOLE his cat named pebbles!!!")
    five = input("Type Message:")
    print("And it dosent even stop their, after Jim-bob found out stephanie stole pebbles,")
    print("he went to her house and took her SINK!!!")
    six = input("Type Message:")
    print("I KNOW RIGHT!")
    print("And then her house flooded!")
    seven = input("Type Message:")
    print("AND then now shes in the hospitle and she is in a coma!")
    ten = input("Type Message:")  
    print(" yeah and beacuse pebbles was inside he drowned and died and now Jim-bob is so sad!")
    elevan = input("Type Message:")
    print("yeah, but its just kinda crazy!")
    eight = input("Type Message:")
    print(f"Well i have to go do some stuff ill text you later {name}!")
    nine = input("Type Message:")
    print(" bye!")
