print("Hello girllll its me Samtha from the bus stop!")
one = input("Type Message:")
print("Wait im sorry whats your name again i need to save your contact?")
name = input("Type Message:")
print(f"{name} is such a cool name!")
two = input("Type Message:")
print ("Do you wanna hear what happened with stephanie and jim-bob!?")
three = input ("Enter yes or no: ")
if three == "no" :
    print("oh okay then i have nothing to tell you...")
    ten = input("Type Message:")
    print("im gonna go, bye.")
if three == "yes" :
    print("okay so Jim-bob told Stephanie she dident wannabe freinds with him so guess what she did!")
    four = input("Type Message:")
    print("She STOLE his cat pebbles!!!")
    five = input("Type Message:")
    print("And it dosent even stop their, after Jim-bob found out stephanie stole pebbles,")
    print("he went to her house and took her SINK!!!")
    six = input("Type Message:")
    print("I KNOW RIGHT!")
    print("And now theirs a crazy rumor going around that her hands smell like garbage beacuse she can't wash them!")
    seven = input("Type Message:")
    print("yeah, but its just kinda crazy!")
    eight = input("Type Message:")
    print("Well i have to go do some stuff ill text you later!")
    nine = input("Type Message:")
    print(" bye!")
